theme: jekyll-theme-hacker
title: Peter Phan
description: Freelancer

favicon: assets/images/favicon.ico

# Cấu hình tự động áp dụng layout cho toàn bộ thư mục con
defaults:
  - scope:
      path: "" # "" nghĩa là áp dụng cho toàn bộ dự án
    values:
      layout: default
