theme: jekyll-theme-hacker
title: Peter Phan
description: Freelancer

favicon: "./assets/favicon.ico"

plugins:
  - jekyll-seo-tag

# Cấu hình tự động áp dụng layout cho toàn bộ thư mục con
defaults:
  - scope:
      path: "" # "" nghĩa là áp dụng cho toàn bộ dự án
    values:
      layout: default
